filename_dictionary : {
    "ratings": "BX-Book-Ratings.csv",
    "users": "BX-Users.csv",
    "books": "BX-Books.csv"
}


encoding: latin-1
seperator: ";"
min_books_to_read : 200
min_number_of_ratings : 50

neighbors_size: 5